# Generated by Django 6.0.8 on 2026-08-11 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_remove_appointment_unique_doctor_appointment_slot_and_more'),
        ('patients', '0002_alter_patient_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_type', models.CharField(choices=[('EXEMPT', 'Exempt'), ('GST', 'GST'), ('OTHER', 'Other')], default='EXEMPT', max_length=20)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Billing',
                'verbose_name_plural': 'Billings',
                'db_table': 'billings',
                'ordering': ['-bill_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('ONLINE', 'Online')], max_length=20)),
                ('payment_type', models.CharField(choices=[('ADVANCE', 'Advance'), ('PARTIAL', 'Partial'), ('FINAL', 'Final')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.billing')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
