# Generated by Django 6.0.8 on 2026-08-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
