# Generated by Django 6.0.8 on 2026-08-07 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('specialization', models.CharField(choices=[('GENERAL_PHYSICIAN', 'General Physician'), ('CARDIOLOGIST', 'Cardiologist'), ('DERMATOLOGIST', 'Dermatologist'), ('ENT', 'ENT Specialist'), ('GYNECOLOGIST', 'Gynecologist'), ('NEUROLOGIST', 'Neurologist'), ('OPHTHALMOLOGIST', 'Ophthalmologist'), ('ORTHOPEDIC', 'Orthopedic'), ('PEDIATRICIAN', 'Pediatrician'), ('PSYCHIATRIST', 'Psychiatrist'), ('RADIOLOGIST', 'Radiologist'), ('SURGEON', 'Surgeon')], max_length=50)),
                ('qualification', models.CharField(max_length=200)),
                ('experience', models.PositiveIntegerField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_LEAVE', 'On Leave'), ('NOT_AVAILABLE', 'Not Available')], default='AVAILABLE', max_length=20)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'db_table': 'doctors',
                'ordering': ['doctor_id'],
            },
        ),
    ]
